application/models.py
from application import app, db

class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True,  unique=True)
    ingredients = db.Column(db.String(256), index=True)
    need_for_shaker = db.Column(db.Boolean, default=False)
    
    def __init__(self, name: str, ingredients: str, need_for_shaker):
        self.name = name
        self.ingredients = ingredients
        self.need_for_shaker = need_for_shaker
    
    def __repr__(self):
        return '<Recipe {}>'.format(self.name)

class Alcohol(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    
    def __repr__(self):
        return '<Alcohol {}>'.format(self.name)
    

application/main/forms.py
from flask import request, flash
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, FieldList
from wtforms.validators import DataRequired, ValidationError, EqualTo, Length
from application.models import Recipe

class RecipeForm(FlaskForm):
    name = StringField(validators=[DataRequired()])
    alcohol_name = FieldList(StringField())
    alcohol_amount = FieldList(StringField())
    ingredient_name = FieldList(StringField())
    ingredient_amount = FieldList(StringField())
    need_shaker = BooleanField('Shaker needed')
    submit = SubmitField('')

class RecipeAddForm(RecipeForm):
    submit = SubmitField('Add Recipe')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def validate_name(self, name):
        recipe = Recipe.query.filter_by(name=name.data).first()
        if recipe is not  None:
            flash('Recipe already exists!')
            raise ValidationError('Recipe with this name already exists')
        
class RecipeUpdateForm(RecipeForm):
    submit = SubmitField('Update Recipe')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

application/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
bootstrap = Bootstrap(app)

from application.main import bp as main_bp
app.register_blueprint(main_bp)

from application import models

application/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from application.main import routes

application/main/routes.py
from flask import render_template, redirect, request, url_for, flash
from application import db
from application.main import bp
from application.main.forms import RecipeAddForm, RecipeUpdateForm
from application.models import Recipe, Alcohol
from sqlalchemy import and_

@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
def index():
    recipes = Recipe.query.order_by(Recipe.name.asc()).all()
    alcohols = Alcohol.query.order_by(Alcohol.name.asc()).all()
    alcohols_names = [alcohol.name for alcohol in alcohols]

    if request.method == 'POST' and request.form.getlist('alcohols_filter') != []:
        checked_boxes = request.form.getlist('alcohols_filter')
            
        filter_values = [filter for filter in alcohols_names if filter not in checked_boxes]
            
        recipes = Recipe.query.filter(and_(Recipe.ingredients.notlike(f"%{filter}%") for filter in filter_values)).all()
                
        return render_template('index.html', recipes=recipes, alcohols=alcohols)
    
    return render_template('index.html', recipes=recipes, alcohols=alcohols)

@bp.route('/add-recipe', methods=['GET', 'POST'])
def add_recipe():
    form = RecipeAddForm()
    
    if form.validate_on_submit():
        recipe_name = form.name.data.capitalize()
        shaker_needed = form.need_shaker.data
        ingredients = []
        alcohols = []
        
        if form.alcohol_name.data:
            for item in zip(form.alcohol_name.data, form.alcohol_amount.data):
                if item[0] != "":
                    alcohols.append(item[0].capitalize())
                    ingredient = " ".join(item)
                    ingredients.append(ingredient)
                
        if form.ingredient_name.data:
            for item in zip(form.ingredient_name.data, form.ingredient_amount.data):
                if item[0] != "" and item[1] != "":
                    ingredient = " ".join(item)
                    ingredients.append(ingredient)
                
        ingredients_to_insert = ", ".join(ingredients)
        
        recipe = Recipe(recipe_name, ingredients_to_insert, shaker_needed)
        db.session.add(recipe)
        
        for alcohol in alcohols:
            alcohol_exist = Alcohol.query.filter_by(name=alcohol).first()
            if alcohol_exist is None:
                new_alcohol = Alcohol(name=alcohol)
                db.session.add(new_alcohol)
                
        db.session.commit()
        return redirect(url_for('main.index'))
    
    return render_template('add_recipe.html', form=form)

@bp.route('/update-recipe/<recipe_name>', methods=['GET', 'POST'])
def update_recipe(recipe_name):
    recipe = Recipe.query.filter_by(name=recipe_name).first()
    form = RecipeUpdateForm()
    
    if form.validate_on_submit():
        recipe_name = form.name.data.capitalize()
        shaker_needed = form.need_shaker.data
        ingredients = []
        alcohols = []
        
        if form.alcohol_name.data:
            for item in zip(form.alcohol_name.data, form.alcohol_amount.data):
                if item[0] != "":
                    alcohols.append(item[0].capitalize())
                    ingredient = " ".join(item)
                    ingredients.append(ingredient)
                    
        if form.ingredient_name.data:
            for item in zip(form.ingredient_name.data, form.ingredient_amount.data):
                if item[0] != "" and item[1] != "":
                    ingredient = " ".join(item)
                    ingredients.append(ingredient)
    
        ingredients_to_insert = ", ".join(ingredients)
        
        recipe.name = recipe_name
        recipe.ingredients = ingredients_to_insert
        recipe.need_for_shaker = shaker_needed
        db.session.commit()
        flash('Changes have been saved!')
        return redirect(url_for('main.index'))
    
    elif request.method == 'GET':
        form.name.data = recipe.name
        form.need_shaker.data = recipe.need_for_shaker
    return render_template('update_recipe.html', form=form, recipe=recipe)
        
        

@bp.route('/delete-recipe/<recipe_name>')
def delete_recipe(recipe_name):
    recipe = Recipe.query.filter_by(name=recipe_name).first()
    
    db.session.delete(recipe)
    db.session.commit()
    
    return redirect(url_for('main.index'))
    

application/templates/_recipe.html
<tr>
  <td width="20%">{{ recipe.name }}</td>
  <td width="60%">{{ recipe.ingredients }}</td>
  <td>{% if recipe.need_for_shaker %} YES {% else %} NO {% endif %}</td>
  <td>
    <a href="{{ url_for('main.update_recipe', recipe_name=recipe.name) }}"><button class="btn btn-sm" type="button" id="recipe_update"><i>{{ utils.icon("pencil") }}</i></button></a>
    <a href="{{ url_for('main.delete_recipe', recipe_name=recipe.name) }}"><button class="btn btn-sm" type="button" id="recipe_remove"><i>{{ utils.icon("remove") }}</i></button></a>
  </td>
</tr>

application/templates/add_recipe.html
{% extends "base.html" %}

{% block application_styles -%}
<style type="text/css">
    .formList {
        display:none;
    }
</style>
{% endblock %}

{% block application_content %}
<form action="{{ url_for('main.add_recipe') }}" method="POST" class="form-horizontal">
    {{ form.hidden_tag() }}
    <div class="form-group col-xs-8" style="margin-bottom: 30px;">
        <div class="col-xs-4" style="padding-right: 5px;"> {{ form.name(class_="form-control", placeholder="Recipe's name") }} </div>
        <div class="col-xs-2 text-center" style="padding: 0px 5px;"><button class="btn" type="button" id="addNewAlcohol">Add Alcohol</button></div>
        <div class="col-xs-2" style="padding: 0px 5px;"><button class="btn" type="button" id="addNewIngredient">Add Ingredient</button></div>
    </div>
    
    <div class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-8">
            <label for="Alcohols">Alcohol(s):<br /></label>
        </div>
    </div>
    <!-- Alcohol(s) as main ingredients inputs -->
    <div id="alcoholFieldsContainer" class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-6" id="alcoholFieldContainer1">
            {{ form.alcohol_name(class_="formList") }}
            <input class="form-control" id="alcohol_name-0" name="alcohol_name-0" placeholder="Ingredient" required="true"></br>
        </div>
        <div class="col-xs-2" id="alcoholFieldContainer2">
            {{ form.alcohol_amount(class_="formList") }}
            <input class="form-control" id="alcohol_amount-0" name="alcohol_amount-0" placeholder="Amount"></br>
        </div>
    </div>

    <div class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-8">
            <label for="Alcohols">Other Ingredients:<br /></label>
        </div>
    </div>
    <!-- Other ingredients inputs -->
    <div class="form-group col-xs-8" style="margin-bottom: 0px">
        <div class="col-xs-6" id="ingredientFieldContainer1">
            {{ form.ingredient_name(class_="formList") }}
            <input class="form-control" id="ingredient_name-0" name="ingredient_name-0" placeholder="Ingredient"></br>
        </div>
        <div class="col-xs-2" id="ingredientFieldContainer2">
            {{ form.ingredient_amount(class_="formList") }}
            <input class="form-control" id="ingredient_amount-0" name="ingredient_amount-0" placeholder="Amount"></br>
        </div>
    </div>

    <div class="form-group col-xs-8">
        <div class="col-xs-6">{{ form.need_shaker.label }} {{ form.need_shaker() }}</div>
        <div class="col-xs-2">{{ form.submit(class_='btn pull-right') }}</div>
    </div>
    
</form>
{% endblock %}

{% block application_scripts %}
{{super()}}
<script>
var alcohol_field_num = 1;
var ingredient_field_num = 1;
$('#addNewAlcohol').click(function(){
    var newInput = $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "alcohol_name-" + alcohol_field_num)
        .attr("name", "alcohol_name-" + alcohol_field_num)
        .attr("placeholder", "Ingredient")
    var newUnitInput =  $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "alcohol_amount-" + alcohol_field_num)
        .attr("name", "alcohol_amount-" + alcohol_field_num)
        .attr("placeholder", "Amount")
    $("#alcoholFieldContainer1").append(newInput)
    $("#alcoholFieldContainer2").append(newUnitInput)
    alcohol_field_num++; 
});

$('#addNewIngredient').click(function(){
    var newInput = $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "ingredient_name-" + ingredient_field_num)
        .attr("name", "ingredient_name-" + ingredient_field_num)
        .attr("placeholder", "Ingredient")
    var newUnitInput =  $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "ingredient_amount-" + ingredient_field_num)
        .attr("name", "ingredient_amount-" + ingredient_field_num)
        .attr("placeholder", "Amount")
    $("#ingredientFieldContainer1").append(newInput)
    $("#ingredientFieldContainer2").append(newUnitInput)
    ingredient_field_num++; 
});
</script>
{% endblock %}

application/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles -%}
{{super()}}
<style>
    a, a:link, a:hover, a:visited {
        color: inherit;
        text-decoration: none;;
    }

</style>
{% block application_styles %}{% endblock %}
{% endblock styles %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{{ url_for('main.index') }}" class="navbar-brand">Cocktails</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.add_recipe') }}">Add recipe</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% endwith %}

    {# application content needs to be provided in the app_content block #}
    {% block application_content %}{% endblock %}
    {% block footer %}{% endblock %}
{% endblock %}

{% block scripts %}
{{super()}}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
    function call_without_reload(elem, url) {
        $(elem).bind('click', function() {
            $.getJSON(url,
                function(data){
                    //do nothing
                });
        return false;
        });
    }
</script>
{% block application_scripts %}{% endblock %}
{% endblock %}

application/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block application_styles -%}
{{super()}}
<style type="text/css">
    .well.sidebar-nav{
        position: fixed;
    }

    .column {
        height: 100%;
        overflow: auto;

    }

    #sidebar {
        padding-top: 30px;
        padding-left: 40px;
        padding-right: 40px;

        border: 1px;
        height: 100%;
    }

    #recipe_update {

    }

</style>
{% endblock %}

{% block application_content %}
    <div class="col-xs-12 col-sm-9" style="padding-left: 0px;">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Recipe Name</th>
                    <th scope="col">Ingredients</th>
                    <th scope="col">Shaker?</th>
                </tr>
            </thead>
            <tbody>
        {% for recipe in recipes %}
            {% include '_recipe.html' %}
        {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="column col-xs-6 col-sm-3 sidebar-offcanvas sidebar-nav-fixed" id="sidebar">
        <form class="form-horizontal" action="{{ url_for('main.index') }}" method="POST">
            {% for alcohol in alcohols %}
                <input type="checkbox" class="form-check-input" name="alcohols_filter" value="{{ alcohol.name }}"> {{alcohol.name}}
                <br />
            {% endfor %}
            <button type="submit" class="btn" style="margin-top: 10px;">Search</button>
        </form>
    </div>
{% endblock %}

{% block application_scripts %}
{{super()}}
<script>

</script>
{% endblock %}

application/templates/update_recipe.html
{% extends "base.html" %}

{% block application_styles -%}
<style type="text/css">
    .formList {
        display:none;
    }
</style>
{% endblock %}

{% block application_content %}
<form action="{{ url_for('main.update_recipe', recipe_name=recipe.name) }}" method="POST" class="form-horizontal">
    {{ form.hidden_tag() }}
    <div class="form-group col-xs-8" style="margin-bottom: 30px;">
        <div class="col-xs-4" style="padding-right: 5px;"> {{ form.name(class_="form-control", placeholder="Recipe's name") }} </div>
        <div class="col-xs-2 text-center" style="padding: 0px 5px;"><button class="btn" type="button" id="addNewAlcohol">Add Alcohol</button></div>
        <div class="col-xs-2" style="padding: 0px 5px;"><button class="btn" type="button" id="addNewIngredient">Add Ingredient</button></div>
    </div>
    
    <div class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-8">
            <label for="Alcohols">Alcohol(s):<br /></label>
        </div>
    </div>
    <!-- Alcohol(s) as main ingredients inputs -->
    <div id="alcoholFieldsContainer" class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-6" id="alcoholFieldContainer1">
            {{ form.alcohol_name(class_="formList") }}
            <input class="form-control" id="alcohol_name-0" name="alcohol_name-0" placeholder="Ingredient" required="true"></br>
        </div>
        <div class="col-xs-2" id="alcoholFieldContainer2">
            {{ form.alcohol_amount(class_="formList") }}
            <input class="form-control" id="alcohol_amount-0" name="alcohol_amount-0" placeholder="Amount"></br>
        </div>
    </div>

    <div class="form-group col-xs-8" style="margin-bottom: 0px;">
        <div class="col-xs-8">
            <label for="Alcohols">Other Ingredients:<br /></label>
        </div>
    </div>
    <!-- Other ingredients inputs -->
    <div class="form-group col-xs-8" style="margin-bottom: 0px">
        <div class="col-xs-6" id="ingredientFieldContainer1">
            {{ form.ingredient_name(class_="formList") }}
            <input class="form-control" id="ingredient_name-0" name="ingredient_name-0" placeholder="Ingredient"></br>
        </div>
        <div class="col-xs-2" id="ingredientFieldContainer2">
            {{ form.ingredient_amount(class_="formList") }}
            <input class="form-control" id="ingredient_amount-0" name="ingredient_amount-0" placeholder="Amount"></br>
        </div>
    </div>

    <div class="form-group col-xs-8">
        <div class="col-xs-6">{{ form.need_shaker.label }} {{ form.need_shaker() }}</div>
        <div class="col-xs-2">{{ form.submit(class_='btn pull-right') }}</div>
    </div>
    
</form>
{% endblock %}

{% block application_scripts %}
{{super()}}
<script>
var alcohol_field_num = 1;
var ingredient_field_num = 1;
$('#addNewAlcohol').click(function(){
    var newInput = $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "alcohol_name-" + alcohol_field_num)
        .attr("name", "alcohol_name-" + alcohol_field_num)
        .attr("placeholder", "Ingredient")
        .attr("value", "")
    var newUnitInput =  $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "alcohol_amount-" + alcohol_field_num)
        .attr("name", "alcohol_amount-" + alcohol_field_num)
        .attr("placeholder", "Amount")
    $("#alcoholFieldContainer1").append(newInput)
    $("#alcoholFieldContainer2").append(newUnitInput)
    alcohol_field_num++; 
});

$('#addNewIngredient').click(function(){
    var newInput = $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "ingredient_name-" + ingredient_field_num)
        .attr("name", "ingredient_name-" + ingredient_field_num)
        .attr("placeholder", "Ingredient")
    var newUnitInput =  $("<input></br>")
        .attr("class", "form-control")
        .attr("id", "ingredient_amount-" + ingredient_field_num)
        .attr("name", "ingredient_amount-" + ingredient_field_num)
        .attr("placeholder", "Amount")
    $("#ingredientFieldContainer1").append(newInput)
    $("#ingredientFieldContainer2").append(newUnitInput)
    ingredient_field_num++; 
});
</script>
{% endblock %}